####################
# CTscanner system #
####################
/gate/world/daughters/name CTscanner
/gate/world/daughters/insert box
/gate/CTscanner/placement/setTranslation 0.357 -0.207 261.0 mm
/gate/CTscanner/geometry/setXLength 143.017 mm
/gate/CTscanner/geometry/setYLength 113.696 mm
/gate/CTscanner/geometry/setZLength 1. mm
/gate/CTscanner/setMaterial Vacuum
/gate/CTscanner/vis/forceWireframe
/gate/CTscanner/vis/setColor white

#############           ############
# CTSCANNER #   ---->   #  MODULE  #
#############           ############
/gate/CTscanner/daughters/name module
/gate/CTscanner/daughters/insert box
/gate/module/geometry/setXLength 143.017 mm
/gate/module/geometry/setYLength 113.696 mm
/gate/module/geometry/setZLength  1. mm
/gate/module/setMaterial Vacuum
/gate/module/vis/forceWireframe
/gate/module/vis/setColor white

############           #############
#  MODULE  #   ---->   # CLUSTER_0 #
############           #############
/gate/module/daughters/name cluster
/gate/module/daughters/insert box
/gate/cluster/geometry/setXLength 143.017 mm
/gate/cluster/geometry/setYLength 113.696 mm
/gate/cluster/geometry/setZLength  1. mm
/gate/cluster/setMaterial Vacuum
/gate/cluster/vis/forceWireframe
/gate/cluster/vis/setColor white

############             #############           ###########
#  MODULE  #   ---->     # CLUSTER_0 #   ---->   # PIXEL_0 #
############             #############           ###########
/gate/cluster/daughters/name pixel
/gate/cluster/daughters/insert box
/gate/pixel/geometry/setXLength 299.2 um
/gate/pixel/geometry/setYLength 299.2 um
/gate/pixel/geometry/setZLength 1. mm
/gate/pixel/setMaterial CsI
/gate/pixel/vis/setColor red
/gate/pixel/vis/setVisible 0

# REPEAT PIXEl_0
/gate/pixel/repeaters/insert cubicArray
/gate/pixel/cubicArray/setRepeatNumberX 478
/gate/pixel/cubicArray/setRepeatNumberY 380
/gate/pixel/cubicArray/setRepeatNumberZ   1
/gate/pixel/cubicArray/setRepeatVector 299.2 299.2 0.00 um
/gate/pixel/cubicArray/autoCenter true

# ATTACH SYSTEM
/gate/systems/CTscanner/module/attach module
/gate/systems/CTscanner/cluster_0/attach cluster
/gate/systems/CTscanner/pixel_0/attach pixel

# ATTACH LAYER
/gate/pixel/attachCrystalSD
