/gate/output/tree/enable
/gate/output/tree/addFileName {ResName}
/gate/output/tree/hits/disable
/gate/output/tree/addCollection Singles

/gate/output/tree/Singles/branches/runID/disable
/gate/output/tree/Singles/branches/sourceID/disable
/gate/output/tree/Singles/branches/sourcePosX/disable
/gate/output/tree/Singles/branches/sourcePosY/disable
/gate/output/tree/Singles/branches/sourcePosZ/disable
/gate/output/tree/Singles/branches/time/disable
/gate/output/tree/Singles/branches/comptonCrystal/disable
/gate/output/tree/Singles/branches/RayleighCrystal/disable
/gate/output/tree/Singles/branches/comptVolName/disable
/gate/output/tree/Singles/branches/RayleighVolName/disable
/gate/output/tree/Singles/branches/rotationAngle/disable
/gate/output/tree/Singles/branches/axialPos/disable
/gate/output/tree/Singles/branches/componentsIDs/disable

#/gate/actor/addActor DoseActor          dose
#/gate/actor/dose/save                   /path/to
#/gate/actor/dose/attachTo               phantom
#/gate/actor/dose/stepHitType            random
#/gate/actor/dose/setSize                68.424 68.424 68.424 mm
#/gate/actor/dose/setResolution          100 100 100
#/gate/actor/dose/enableEdep             true
#/gate/actor/dose/enableUncertaintyEdep  true
#/gate/actor/dose/enableSquaredEdep      true
#/gate/actor/dose/enableDose             true
#/gate/actor/dose/normaliseDoseToMax     true
