/gate/source/addSource xraygun
/gate/source/verbose 0
/gate/source/xraygun/setActivity 100000000. becquerel
/gate/source/xraygun/gps/verbose 0
/gate/source/xraygun/gps/particle gamma
/gate/source/xraygun/gps/energytype Arb
/gate/source/xraygun/gps/histname arb
/gate/source/xraygun/gps/emin 10.00 keV
/gate/source/xraygun/gps/emax 150.00 keV
/gate/source/xraygun/gps/histpoint 0.010 0
/gate/source/xraygun/gps/histpoint 0.011 0
/gate/source/xraygun/gps/histpoint 0.012 0
/gate/source/xraygun/gps/histpoint 0.013 1
/gate/source/xraygun/gps/histpoint 0.014 3
/gate/source/xraygun/gps/histpoint 0.015 7
/gate/source/xraygun/gps/histpoint 0.016 14
/gate/source/xraygun/gps/histpoint 0.017 30
/gate/source/xraygun/gps/histpoint 0.018 48
/gate/source/xraygun/gps/histpoint 0.019 63
/gate/source/xraygun/gps/histpoint 0.020 79
/gate/source/xraygun/gps/histpoint 0.021 97
/gate/source/xraygun/gps/histpoint 0.022 117
/gate/source/xraygun/gps/histpoint 0.023 136
/gate/source/xraygun/gps/histpoint 0.024 157
/gate/source/xraygun/gps/histpoint 0.025 174
/gate/source/xraygun/gps/histpoint 0.026 191
/gate/source/xraygun/gps/histpoint 0.027 204
/gate/source/xraygun/gps/histpoint 0.028 218
/gate/source/xraygun/gps/histpoint 0.029 225
/gate/source/xraygun/gps/histpoint 0.030 235
/gate/source/xraygun/gps/histpoint 0.031 237
/gate/source/xraygun/gps/histpoint 0.032 242
/gate/source/xraygun/gps/histpoint 0.033 246
/gate/source/xraygun/gps/histpoint 0.034 245
/gate/source/xraygun/gps/histpoint 0.035 249
/gate/source/xraygun/gps/histpoint 0.036 247
/gate/source/xraygun/gps/histpoint 0.037 246
/gate/source/xraygun/gps/histpoint 0.038 243
/gate/source/xraygun/gps/histpoint 0.039 241
/gate/source/xraygun/gps/histpoint 0.040 233
/gate/source/xraygun/gps/histpoint 0.041 229
/gate/source/xraygun/gps/histpoint 0.042 228
/gate/source/xraygun/gps/histpoint 0.043 221
/gate/source/xraygun/gps/histpoint 0.044 214
/gate/source/xraygun/gps/histpoint 0.045 211
/gate/source/xraygun/gps/histpoint 0.046 204
/gate/source/xraygun/gps/histpoint 0.047 199
/gate/source/xraygun/gps/histpoint 0.048 196
/gate/source/xraygun/gps/histpoint 0.049 190
/gate/source/xraygun/gps/histpoint 0.050 184
/gate/source/xraygun/gps/histpoint 0.051 178
/gate/source/xraygun/gps/histpoint 0.052 172
/gate/source/xraygun/gps/histpoint 0.053 165
/gate/source/xraygun/gps/histpoint 0.054 157
/gate/source/xraygun/gps/histpoint 0.055 153
/gate/source/xraygun/gps/histpoint 0.056 149
/gate/source/xraygun/gps/histpoint 0.057 165
/gate/source/xraygun/gps/histpoint 0.058 182
/gate/source/xraygun/gps/histpoint 0.059 199
/gate/source/xraygun/gps/histpoint 0.060 208
/gate/source/xraygun/gps/histpoint 0.061 165
/gate/source/xraygun/gps/histpoint 0.062 122
/gate/source/xraygun/gps/histpoint 0.063 112
/gate/source/xraygun/gps/histpoint 0.064 104
/gate/source/xraygun/gps/histpoint 0.065 101
/gate/source/xraygun/gps/histpoint 0.066 94
/gate/source/xraygun/gps/histpoint 0.067 103
/gate/source/xraygun/gps/histpoint 0.068 110
/gate/source/xraygun/gps/histpoint 0.069 97
/gate/source/xraygun/gps/histpoint 0.070 81
/gate/source/xraygun/gps/histpoint 0.071 70
/gate/source/xraygun/gps/histpoint 0.072 60
/gate/source/xraygun/gps/histpoint 0.073 55
/gate/source/xraygun/gps/histpoint 0.074 52
/gate/source/xraygun/gps/histpoint 0.075 45
/gate/source/xraygun/gps/histpoint 0.076 48
/gate/source/xraygun/gps/histpoint 0.077 45
/gate/source/xraygun/gps/histpoint 0.078 42
/gate/source/xraygun/gps/histpoint 0.079 38
/gate/source/xraygun/gps/histpoint 0.080 33
/gate/source/xraygun/gps/histpoint 0.081 32
/gate/source/xraygun/gps/histpoint 0.082 23
/gate/source/xraygun/gps/histpoint 0.083 23
/gate/source/xraygun/gps/histpoint 0.084 20
/gate/source/xraygun/gps/histpoint 0.085 17
/gate/source/xraygun/gps/histpoint 0.086 13
/gate/source/xraygun/gps/histpoint 0.087 11
/gate/source/xraygun/gps/histpoint 0.088 8
/gate/source/xraygun/gps/histpoint 0.089 5
 /gate/source/xraygun/gps/arbint Lin
/gate/source/xraygun/gps/type Plane
/gate/source/xraygun/gps/shape Rectangle
/gate/source/xraygun/gps/halfx 5. um
/gate/source/xraygun/gps/halfy 5. um
/gate/source/xraygun/gps/mintheta 0  deg
/gate/source/xraygun/gps/maxtheta  3.6 deg
/gate/source/xraygun/gps/centre -1.146 0.0927 -837. mm
/gate/source/xraygun/gps/angtype iso
/gate/source/list
