/gate/world/daughters/name phantom
/gate/world/daughters/insert cylinder
/gate/phantom/geometry/setRmin 0 mm
/gate/phantom/geometry/setRmax 10.582226936268414 mm
/gate/phantom/geometry/setHeight 54.90677086326788 mm
/gate/phantom/geometry/setPhiStart 0 deg
/gate/phantom/geometry/setDeltaPhi 360 deg
/gate/phantom/setMaterial Plexiglass
/gate/phantom/daughters/name cavity
/gate/phantom/daughters/insert ellipsoid
/gate/cavity/geometry/setXLength 0.07546382423382479 mm
/gate/cavity/geometry/setYLength 0.10403169847051526 mm
/gate/cavity/geometry/setZLength 0.07044830647883647 mm
/gate/cavity/setMaterial Vacuum
/gate/phantom/placement/setTranslation  0. 0. 0. mm
/gate/phantom/placement/setRotationAxis 1 0 0
/gate/phantom/placement/setRotationAngle 90 deg
/gate/phantom/attachPhantomSD
/gate/cavity/placement/setTranslation -2.6455567340671036 0.0 -9.540587331638443 mm
/gate/cavity/attachPhantomSD
